spring.datasource.url=jdbc:postgresql://localhost:5432/api_mensageria_db
spring.datasource.username=mensageria_user
spring.datasource.password=salesiano2025

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true